language: cpp

compiler:
  - gcc

before_install:
  - cd /opt
  - sudo wget http://apache.is.co.za/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz
  - sudo tar -xvf zookeeper-3.4.9.tar.gz

before_script:
  - ls
  - cd zookeeper-3.4.9
  - sudo bin/zkServer.sh start
  - cd $TRAVIS_BUILD_DIR/cpp
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ./bin/main
  - ./tests/testFoo

after_script:
  - cd /opt/zookeeper-3.4.9
  - sudo bin/zkServer.sh stop

notifications:
on_success: always
on_failure: always
