language: cpp

compiler:
  - gcc

before_install:
  - sudo rm -rf /etc/apt/sources.list.d/rwky-redis.list
  - sudo add-apt-repository ppa:chris-lea/redis-server -y
  - curl -s http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh/archive.key | sudo apt-key add -
  - wget http://archive.cloudera.com/cdh4/one-click-install/precise/amd64/cdh4-repository_1.0_all.deb
  - sudo dpkg -i cdh4-repository_1.0_all.deb
  - sudo apt-get update -qq
  - sudo apt-get install -y zookeeper-server

before_script:
  - sudo service zookeeper-server init
  - sudo service zookeeper-server start
  - cd cpp
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ./bin/main
  - ./tests/testFoo

after_script:
  - sudo service zookeeper-server stop

notifications:
on_success: always
on_failure: always
