matrix:
  include:
    - language: node_js
      node_js:
        - "7"
      
      before_script:
        - cd rest-api

      # Tests code quality with TSLint.
      script:
        - ./node_modules/tslint/bin/tslint -c tslint.json 'src/**/*.ts'


    - language: cpp
      compiler: gcc

      addons:
        apt:
          sources:
            - boost-latest
          packages:
            - libboost1.55-all-dev

      before_script:
        - cd cpp
        - mkdir build
        - cd build
        - cmake -DENABLE_ZOOKEEPER=OFF -DENABLE_LATEST_BOOST=ON ..
        - make testFoo

      # Runs unit tests
      script:
        - ./tests/testFoo

notifications:
  on_success: always
  on_failure: always
