language: cpp

compiler:
  - gcc

before_script:
  - cd cpp
  - mkdir build
  - cd build
  - cmake -ENABLE_ZOOKEEPER=OFF ..
  - make testFoo

script:
  - ./tests/testFoo

notifications:
on_success: always
on_failure: always
