language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.53-all-dev

before_script:
  - cd cpp
  - mkdir build
  - cd build
  - cmake -DENABLE_ZOOKEEPER=OFF ..
  - make testFoo

script:
  - ./tests/testFoo

notifications:
on_success: always
on_failure: always
